export const stories = [
  {
    profileImg: "/stories/profile-1.png",
    profileName: "Behance",
    title: ["Designing quiet worlds", "where motion tells", "the whole story"],
    linkLabel: "Read Story",
    linkSrc: "/stories/designing-quiet-worlds",
    storyImg: "/stories/story-1.jpg",
    slug: "designing-quiet-worlds",
    date: "2025",
    category: "Design",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "Dribbble",
    title: ["Light, reflection,", "and invisible form", "in digital motion"],
    linkLabel: "Read Story",
    linkSrc: "/stories/light-reflection-form",
    storyImg: "/stories/story-2.jpg",
    slug: "light-reflection-form",
    date: "2025",
    category: "Art Direction",
  },
  {
    profileImg: "/stories/profile-3.png",
    profileName: "Awwwards",
    title: ["A motion identity", "built around silence,", "texture, and time"],
    linkLabel: "Read Story",
    linkSrc: "/stories/motion-identity-silence",
    storyImg: "/stories/story-3.jpg",
    slug: "motion-identity-silence",
    date: "2025",
    category: "Branding",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "Adobe",
    title: ["When design meets", "science fiction,", "everything glows"],
    linkLabel: "Read Story",
    linkSrc: "/stories/design-meets-scifi",
    storyImg: "/stories/story-4.jpg",
    slug: "design-meets-scifi",
    date: "2025",
    category: "Technology",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "Dribbble",
    title: ["Cinematic branding", "for the in-between", "moments of light"],
    linkLabel: "Read Story",
    linkSrc: "/stories/cinematic-branding",
    storyImg: "/stories/story-5.jpg",
    slug: "cinematic-branding",
    date: "2025",
    category: "Motion",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "Adobe",
    title: ["Interactive motion", "built to move softly", "and stay longer"],
    linkLabel: "Read Story",
    linkSrc: "/stories/interactive-motion",
    storyImg: "/stories/story-6.jpg",
    slug: "interactive-motion",
    date: "2025",
    category: "Interaction",
  },
];
